name: Terraform validate

on:
  push:
    branches:
      - test-tf-ci

jobs:
  test-tf-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.15.6"
      - run: |
          terraform init -backend=false
          terraform validate
